# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Nyanbit with Python 3.9

on:
  pull_request:
    branches: ['master']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9']

    env:
      HOST: 'localhost'
      USERID: 'root'
      PASSWORD: ${{ secrets.PASSWORD }}
      DBNAME: 'nyanbit_db'
      TEST_ID: '111111111111111111'
      TEST_NAME: 'TEST'

    steps:
      - uses: actions/checkout@v4

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Set up MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          my-cnf: |
            innodb_log_file_size=256MB
            innodb_buffer_pool_size=512MB
            max_allowed_packet=16MB
            max_connections=50
            local_infile=1
          root-password: ${{ secrets.PASSWORD }}

      - name: Create DB
        run: |
          mysql -u root -p'${{ secrets.PASSWORD }}' -e 'CREATE DATABASE nyanbit_db DEFAULT CHARACTER SET UTF8;'
          mysql -u root -p'${{ secrets.PASSWORD }}' -e 'USE nyanbit_db;'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          python -m pytest tests
