# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Nyanbit with Python 3.9

on:
  pull_request:
    branches: ['master']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9']

    env:
      HOST: 'localhost'
      USERID: 'root'
      PASSWORD: ${{ secrets.PASSWORD }}
      DBNAME: 'nyanbit_db'
      TEST_ID: '111111111111111111'
      TEST_NAME: 'TEST'

    steps:
      - uses: actions/checkout@v4

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql database: ${{ secrets.DBNAME }}
          mysql root password: ${{ secrets.PASSWORD }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          python -m pytest tests
